/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define yywrap() 1
#define YY_SKIP_YYWRAP
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 70
#define YY_END_OF_BUFFER 71
static yyconst short int yy_accept[276] =
    {   0,
        0,    0,   71,   69,   67,   68,   52,   69,   69,   59,
       60,   69,   63,   64,   57,   55,   62,   56,   51,   58,
        3,    2,   61,   53,   50,   54,   48,   48,   48,   48,
       48,   48,   48,   48,   48,   48,   48,   48,   48,   48,
       48,   48,   65,   69,   66,   67,   30,    0,    7,    0,
        0,    0,    0,   17,   26,   22,    0,    0,   15,   24,
       18,   25,   19,   49,    5,    0,    9,   16,    5,    3,
        0,   10,   10,   10,    2,   32,   29,   31,   28,   33,
       48,   48,   48,   48,   48,   48,   48,   48,   39,   48,
       48,   48,   48,   48,   48,   35,   48,   48,   48,   48,

       48,   48,   48,   48,   48,   48,   48,   23,   27,    0,
        0,    6,    0,    0,   10,    5,    0,    0,    9,   10,
        5,    0,   10,   10,    0,    5,    4,    4,   20,   21,
       48,   48,   48,   48,   48,   48,   48,   48,   48,   48,
       48,   48,   40,   48,   11,   48,   48,   48,   48,   48,
       48,   48,   48,   48,   48,   48,   48,   48,   48,   48,
        0,    0,    0,    5,    8,    0,    5,    5,    5,   12,
       48,   45,   48,   48,   48,   48,   36,   47,   48,   48,
       43,   48,   48,   48,   48,   48,   48,   48,   48,   48,
       48,   48,   48,   48,    0,    0,    5,    5,    5,    5,

        5,   44,   13,   48,   48,   48,   48,   48,   48,   48,
       48,   48,   48,   48,   48,   14,   48,   48,   38,    0,
        0,   48,   48,   48,   41,   34,   37,   48,   48,   48,
        0,    0,   48,   46,   48,   48,   48,    0,    0,   42,
        0,    0,    0,    0,    1,    0,    0,    0,    0,    0,
        0,    1,    1,    1,    0,    0,    0,    0,    1,    1,
        0,    0,    0,    0,    1,    1,    1,    1,    1,    1,
        1,    0,    1,    1,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    7,    1,    8,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   20,
       20,   20,   20,   20,   20,   21,   21,    1,   22,   23,
       24,   25,    1,    1,   26,   26,   26,   26,   27,   28,
       29,   29,   29,   29,   29,   30,   29,   29,   29,   29,
       29,   29,   29,   29,   29,   29,   29,   31,   29,   29,
        1,   32,    1,    1,   29,    1,   33,   34,   35,   36,

       37,   38,   39,   40,   41,   29,   42,   43,   44,   45,
       46,   47,   29,   48,   49,   50,   51,   52,   53,   54,
       55,   56,   57,   58,   59,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[60] =
    {   0,
        1,    1,    2,    3,    1,    1,    4,    1,    1,    1,
        5,    6,    1,    1,    6,    1,    7,    1,    8,    8,
        8,    1,    1,    1,    1,    9,    9,    9,    9,    9,
        9,    1,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    1,    1,    1
    } ;

static yyconst short int yy_base[290] =
    {   0,
        0,    0,  650,  651,   58,  651,  625,   55,   59,  624,
       55,  615,  651,  651,  622,   51,  651,   52,   50,   54,
       65,   84,  651,  622,   50,   56,    0,  593,   42,   66,
       52,   64,   48,  597,   70,  596,  604,   73,  585,  594,
      592,  597,  651,   59,  651,  118,  651,  104,  651,  633,
       89,  598,  589,  651,  651,  651,  623,  114,  651,  651,
      651,  651,  651,  651,  143,  619,    0,  651,  101,  128,
      155,  121,  137,  174,  196,  607,  651,  651,  651,  606,
        0,  579,  582,  590,  577,  592,  579,  585,  571,  572,
      569,  569,  572,  569,  566,    0,  565,  569,   77,  567,

       96,  113,  571,  564,  128,   91,  569,  651,  651,  571,
      573,  651,  597,  596,  169,  147,  592,  166,    0,  205,
      177,  215,  184,  218,  221,  224,    0,    0,  651,  651,
      558,  560,  569,  564,  552,  178,  566,  564,  560,  552,
      558,  561,    0,  547,    0,  553,  550,  539,  541,  543,
      550,  536,  534,  534,  546,  536,  540,  544,  546,  535,
      536,  533,  227,  230,  651,  236,  244,  258,  250,    0,
      533,    0,  524,  532,  521,  528,    0,    0,  522,  519,
        0,  519,  519,  516,  528,  518,  522,  527,  526,  522,
      511,  516,  502,  514,  505,  498,  270,  264,  274,  279,

      289,    0,    0,  503,  498,  502,  485,  471,  472,  480,
      476,  476,  460,  469,  471,    0,  462,  455,    0,  436,
      420,  404,  404,  416,    0,    0,    0,  414,  359,  349,
      333,  296,  292,    0,  280,  291,  288,  316,  299,    0,
      139,  307,  302,  301,  195,  302,  255,  263,  174,  259,
      213,    0,  310,  330,  257,  311,  275,  299,    0,  389,
      445,  228,  218,  446,  203,  201,  447,  183,  174,    0,
      150,  133,   93,   62,  651,  462,  471,  474,  476,  485,
      494,  496,  503,  510,  519,  528,  537,  544,  551
    } ;

static yyconst short int yy_def[290] =
    {   0,
      275,    1,  275,  275,  275,  275,  275,  276,  275,  275,
      275,  277,  275,  275,  275,  275,  275,  275,  275,  275,
      278,  278,  275,  275,  275,  275,  279,  279,  279,  279,
      279,  279,  279,  279,  279,  279,  279,  279,  279,  279,
      279,  279,  275,  275,  275,  275,  275,  276,  275,  276,
      275,  275,  275,  275,  275,  275,  275,  275,  275,  275,
      275,  275,  275,  275,  278,  280,  281,  275,   65,  278,
      275,  282,  282,  282,  278,  275,  275,  275,  275,  275,
      279,  279,  279,  279,  279,  279,  279,  279,  279,  279,
      279,  279,  279,  279,  279,  279,  279,  279,  279,  279,

      279,  279,  279,  279,  279,  279,  279,  275,  275,  275,
      275,  275,  275,  275,  282,  282,  280,  280,  281,  282,
      282,  275,  282,  282,  275,  282,   74,   74,  275,  275,
      279,  279,  279,  279,  279,  279,  279,  279,  279,  279,
      279,  279,  279,  279,  279,  279,  279,  279,  279,  279,
      279,  279,  279,  279,  279,  279,  279,  279,  279,  279,
      275,  275,  275,  282,  275,  275,  282,  278,  282,  279,
      279,  279,  279,  279,  279,  279,  279,  279,  279,  279,
      279,  279,  279,  279,  279,  279,  279,  279,  279,  279,
      279,  279,  279,  279,  275,  275,   65,  282,  168,  282,

      282,  279,  279,  279,  279,  279,  279,  279,  279,  279,
      279,  279,  279,  279,  279,  279,  279,  279,  279,  275,
      275,  279,  279,  279,  279,  279,  279,  279,  279,  279,
      275,  275,  279,  279,  279,  279,  279,  283,  275,  279,
      284,  275,  285,  286,  287,  288,  284,  285,  285,  286,
      286,  287,  287,  275,  288,  289,  285,  286,  254,  275,
      275,  275,  288,  289,  285,  286,  287,  287,  254,  260,
      287,  288,  287,  254,    0,  275,  275,  275,  275,  275,
      275,  275,  275,  275,  275,  275,  275,  275,  275
    } ;

static yyconst short int yy_nxt[711] =
    {   0,
        4,    5,    6,    5,    7,    8,    9,   10,   11,   12,
       13,   14,   15,   16,   17,   18,   19,   20,   21,   22,
       22,   23,   24,   25,   26,   27,   27,   27,   27,   27,
       27,    4,   28,   29,   30,   31,   32,   33,   34,   27,
       35,   27,   36,   27,   27,   27,   27,   37,   38,   39,
       40,   41,   42,   27,   27,   27,   43,   44,   45,   46,
       49,   46,   51,   55,   60,  274,   66,   62,   65,   65,
       65,   67,   77,   78,   61,   63,   64,   68,   56,   79,
       80,   69,  108,   70,   70,   71,   50,   83,   88,   84,
       93,   73,   51,   94,   52,   74,  273,   89,   85,   53,

       69,   73,   75,   75,   75,   86,   90,   96,   91,   49,
       73,   87,  100,  101,   97,  147,  109,   92,   74,   46,
       73,   46,  102,  112,   52,  103,  148,  120,  121,   53,
      121,  158,  113,  159,  150,   50,  272,  120,  121,  123,
      123,  123,  245,  121,   69,  152,   70,   70,   71,  246,
      125,  151,  125,  273,   73,  126,  126,  126,  114,  275,
      153,   65,   65,   65,   73,  123,  123,  123,  156,  115,
      116,   69,  116,   71,   71,   71,  157,  274,  118,  115,
      116,  122,  163,  165,  163,  116,  273,  164,  164,  164,
      249,  122,  127,  127,  127,  123,  123,  123,  253,  128,

      128,  128,  123,  123,  123,  254,  128,  128,  128,  128,
      128,  128,   69,  257,   75,   75,   75,  251,  166,  249,
      166,  272,   73,  167,  167,  167,  173,  174,  125,  251,
      125,  271,   73,  168,  168,  168,  123,  123,  123,  168,
      168,  168,  126,  126,  126,  197,  197,  197,  164,  164,
      164,  169,  258,  169,  199,  199,  199,  198,  245,  198,
      255,  169,  167,  167,  167,  246,  169,  198,  123,  123,
      123,  200,  198,  200,  275,  251,  168,  168,  168,  249,
      265,  200,  123,  123,  123,  201,  200,  201,  197,  197,
      197,  249,  199,  199,  199,  201,   72,  123,  123,  123,

      201,  121,  242,  121,  243,  255,   72,  123,  123,  123,
      242,  121,  243,  253,  261,  251,  121,  251,  249,  238,
      254,  244,  262,  266,  203,  263,  145,  170,  240,  244,
      252,  252,  239,  259,  252,  252,  238,  252,  252,  252,
      252,  252,  252,  252,  252,  252,  252,  252,  252,  252,
      252,  252,  252,  252,  252,  260,  260,  260,  260,  260,
      260,  252,  260,  260,  260,  260,  260,  260,  260,  260,
      260,  260,  260,  260,  260,  260,  260,  260,  260,  260,
      260,  260,  260,  260,  260,  260,  252,  252,  252,  252,
      252,  237,  267,  252,  252,  236,  252,  252,  252,  252,

      268,  252,  252,  269,  252,  252,  252,  270,  270,  270,
      252,  252,  252,  252,  270,  270,  270,  270,  270,  270,
      252,  270,  270,  270,  270,  270,  270,  270,  270,  270,
      270,  270,  270,  270,  270,  270,  270,  270,  270,  270,
      270,  270,  270,  270,  270,  252,  252,  252,  261,  261,
      267,  170,  235,  234,  233,  232,  262,  262,  268,  263,
      263,  269,   48,   48,   48,   48,   48,   48,   48,   48,
       48,   57,  231,   57,   57,   57,   57,   57,   57,   57,
       72,   72,   72,   81,   81,  117,  117,  117,  117,  117,
      117,  117,  117,  117,  119,  230,  119,  119,  119,  119,

      119,  119,  119,  124,  124,  241,  229,  228,  227,  216,
      170,  241,  247,  226,  247,  145,  225,  247,  247,  248,
      224,  248,  248,  248,  248,  248,  248,  248,  250,  170,
      250,  250,  250,  250,  250,  250,  250,  252,  145,  252,
      223,  252,  252,  252,  252,  252,  256,  222,  221,  220,
      219,  218,  256,  264,  217,  216,  264,  215,  264,  264,
      214,  213,  212,  211,  210,  145,  209,  208,  145,  207,
      206,  205,  204,  203,  202,  196,  195,  194,  193,  145,
      192,  191,  190,  189,  188,  187,  186,  185,  184,  183,
      182,  145,  181,  180,  179,  178,  177,  176,  175,  145,

      172,  171,  145,  170,  118,  112,  112,  162,  161,  160,
      155,  154,  149,  146,  145,  144,  143,  142,  141,  140,
      139,  138,  137,  136,  135,  134,  133,  132,  131,  130,
      129,  118,  112,  111,  110,  275,  107,  106,  105,  104,
       99,   98,   95,   82,   76,   59,   58,   54,   47,  275,
        3,  275,  275,  275,  275,  275,  275,  275,  275,  275,
      275,  275,  275,  275,  275,  275,  275,  275,  275,  275,
      275,  275,  275,  275,  275,  275,  275,  275,  275,  275,
      275,  275,  275,  275,  275,  275,  275,  275,  275,  275,
      275,  275,  275,  275,  275,  275,  275,  275,  275,  275,

      275,  275,  275,  275,  275,  275,  275,  275,  275,  275
    } ;

static yyconst short int yy_chk[711] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    5,
        8,    5,    9,   11,   16,  274,   20,   18,   19,   19,
       19,   20,   25,   25,   16,   18,   18,   20,   11,   26,
       26,   21,   44,   21,   21,   21,    8,   29,   31,   29,
       33,   21,   51,   33,    9,   21,  273,   31,   30,    9,

       22,   21,   22,   22,   22,   30,   32,   35,   32,   48,
       22,   30,   38,   38,   35,   99,   44,   32,   21,   46,
       22,   46,   38,   58,   51,   38,   99,   69,   69,   51,
       69,  106,   58,  106,  101,   48,  272,   69,   69,   72,
       72,   72,  241,   69,   70,  102,   70,   70,   70,  241,
       73,  101,   73,  271,   70,   73,   73,   73,   58,   65,
      102,   65,   65,   65,   70,  116,  116,  116,  105,   65,
       65,   71,   65,   71,   71,   71,  105,  269,  118,   65,
       65,   71,  115,  118,  115,   65,  268,  115,  115,  115,
      249,   71,   74,   74,   74,  121,  121,  121,  245,   74,

       74,   74,  123,  123,  123,  245,   74,   74,   74,   74,
       74,   74,   75,  249,   75,   75,   75,  266,  120,  265,
      120,  263,   75,  120,  120,  120,  136,  136,  122,  251,
      122,  262,   75,  122,  122,  122,  124,  124,  124,  125,
      125,  125,  126,  126,  126,  163,  163,  163,  164,  164,
      164,  126,  251,  126,  166,  166,  166,  164,  247,  164,
      255,  126,  167,  167,  167,  247,  126,  164,  169,  169,
      169,  167,  164,  167,  168,  250,  168,  168,  168,  248,
      257,  167,  198,  198,  198,  168,  167,  168,  197,  197,
      197,  257,  199,  199,  199,  168,  197,  200,  200,  200,

      168,  199,  239,  199,  239,  246,  197,  201,  201,  201,
      242,  199,  242,  253,  256,  258,  199,  244,  243,  238,
      253,  239,  256,  258,  237,  256,  236,  235,  233,  242,
      254,  254,  232,  254,  254,  254,  231,  254,  254,  254,
      254,  254,  254,  254,  254,  254,  254,  254,  254,  254,
      254,  254,  254,  254,  254,  254,  254,  254,  254,  254,
      254,  254,  254,  254,  254,  254,  254,  254,  254,  254,
      254,  254,  254,  254,  254,  254,  254,  254,  254,  254,
      254,  254,  254,  254,  254,  254,  254,  254,  254,  260,
      260,  230,  260,  260,  260,  229,  260,  260,  260,  260,

      260,  260,  260,  260,  260,  260,  260,  260,  260,  260,
      260,  260,  260,  260,  260,  260,  260,  260,  260,  260,
      260,  260,  260,  260,  260,  260,  260,  260,  260,  260,
      260,  260,  260,  260,  260,  260,  260,  260,  260,  260,
      260,  260,  260,  260,  260,  260,  260,  260,  261,  264,
      267,  228,  224,  223,  222,  221,  261,  264,  267,  261,
      264,  267,  276,  276,  276,  276,  276,  276,  276,  276,
      276,  277,  220,  277,  277,  277,  277,  277,  277,  277,
      278,  278,  278,  279,  279,  280,  280,  280,  280,  280,
      280,  280,  280,  280,  281,  218,  281,  281,  281,  281,

      281,  281,  281,  282,  282,  283,  217,  215,  214,  213,
      212,  283,  284,  211,  284,  210,  209,  284,  284,  285,
      208,  285,  285,  285,  285,  285,  285,  285,  286,  207,
      286,  286,  286,  286,  286,  286,  286,  287,  206,  287,
      205,  287,  287,  287,  287,  287,  288,  204,  196,  195,
      194,  193,  288,  289,  192,  191,  289,  190,  289,  289,
      189,  188,  187,  186,  185,  184,  183,  182,  180,  179,
      176,  175,  174,  173,  171,  162,  161,  160,  159,  158,
      157,  156,  155,  154,  153,  152,  151,  150,  149,  148,
      147,  146,  144,  142,  141,  140,  139,  138,  137,  135,

      134,  133,  132,  131,  117,  114,  113,  111,  110,  107,
      104,  103,  100,   98,   97,   95,   94,   93,   92,   91,
       90,   89,   88,   87,   86,   85,   84,   83,   82,   80,
       76,   66,   57,   53,   52,   50,   42,   41,   40,   39,
       37,   36,   34,   28,   24,   15,   12,   10,    7,    3,
      275,  275,  275,  275,  275,  275,  275,  275,  275,  275,
      275,  275,  275,  275,  275,  275,  275,  275,  275,  275,
      275,  275,  275,  275,  275,  275,  275,  275,  275,  275,
      275,  275,  275,  275,  275,  275,  275,  275,  275,  275,
      275,  275,  275,  275,  275,  275,  275,  275,  275,  275,

      275,  275,  275,  275,  275,  275,  275,  275,  275,  275
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "TP4.l"
#define INITIAL 0
#line 4 "TP4.l"
#include"TP4.tab.h"
#include<stdio.h>
#include<string.h>
#include<stdlib.h>
#include<ctype.h>

#define YYDEBUG1

extern FILE* yyin;



#line 627 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 41 "TP4.l"

#line 780 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 276 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 651 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 42 "TP4.l"
{;}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 43 "TP4.l"
{yylval.ival = atoi(yytext); return CENTERO;}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 44 "TP4.l"
{yylval.ival = strtol(yytext, NULL, 0); return CENTERO;}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 45 "TP4.l"
{yylval.ival = strtol(yytext, NULL, 0); return CENTERO;} 
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 46 "TP4.l"
{yylval.dval = atof(yytext); return CREAL;}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 47 "TP4.l"
{yylval.ccval = strdup(yytext); return CCARACTER;}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 48 "TP4.l"
{yylval.ccval = strdup(yytext); return LCADENA;}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 49 "TP4.l"
{;} 
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 50 "TP4.l"
{;} 
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 51 "TP4.l"
{;}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 52 "TP4.l"
{return TDATO;}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 53 "TP4.l"
{return TCLASE;}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 54 "TP4.l"
{return CALTIPO;}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 55 "TP4.l"
{return STRUNION;}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 57 "TP4.l"
{return OPASIG;}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 58 "TP4.l"
{return OPASIG;}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 59 "TP4.l"
{return OPASIG;}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 60 "TP4.l"
{return OPASIG;}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 61 "TP4.l"
{return OPASIG;}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 62 "TP4.l"
{return OPASIG;}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 63 "TP4.l"
{return OPASIG;}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 64 "TP4.l"
{return OPASIG;}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 65 "TP4.l"
{return OPASIG;}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 66 "TP4.l"
{return OPINCDEC;}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 67 "TP4.l"
{return OPINCDEC;}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 68 "TP4.l"
{return AND;}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 69 "TP4.l"
{return OR;}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 70 "TP4.l"
{return OPREL;}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 71 "TP4.l"
{return OPREL;}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 72 "TP4.l"
{return OPIGUAL;}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 73 "TP4.l"
{return OPIGUAL;}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 74 "TP4.l"
{return OPCORR;}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 75 "TP4.l"
{return OPCORR;}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 76 "TP4.l"
{return SIOF;}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 77 "TP4.l"
{return IF;}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 78 "TP4.l"
{return ELSE;}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 79 "TP4.l"
{return SWITCH;}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 80 "TP4.l"
{return WHILE;}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 81 "TP4.l"
{return DO;}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 82 "TP4.l"
{return FOR;}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 83 "TP4.l"
{return RETURN;}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 84 "TP4.l"
{return CONTINUE;}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 85 "TP4.l"
{return GOTO;}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 86 "TP4.l"
{return BREAK;}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 87 "TP4.l"
{return CASE;}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 88 "TP4.l"
{return DEFAULT;}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 89 "TP4.l"
{return ENUM;}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 90 "TP4.l"
{yylval.ccval = strdup(yytext); return ID;}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 92 "TP4.l"
{return FLECHA;}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 93 "TP4.l"
{return '=';}   
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 94 "TP4.l"
{return '.';}   
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 95 "TP4.l"
{return '!';}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 96 "TP4.l"
{return '<';}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 97 "TP4.l"
{return '>';}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 98 "TP4.l"
{return '+';}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 99 "TP4.l"
{return '-';}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 100 "TP4.l"
{return '*';}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 101 "TP4.l"
{return '/';}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 102 "TP4.l"
{return '%';}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 103 "TP4.l"
{return '&';}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 104 "TP4.l"
{return ';';}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 105 "TP4.l"
{return ',';}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 106 "TP4.l"
{return '(';}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 107 "TP4.l"
{return ')';}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 108 "TP4.l"
{return '{';}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 109 "TP4.l"
{return '}';} 
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 110 "TP4.l"
{;}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 111 "TP4.l"
{;} 
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 112 "TP4.l"
{;}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 113 "TP4.l"
ECHO;
	YY_BREAK
#line 1213 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 276 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 276 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 275);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 113 "TP4.l"
