/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define yywrap() 1
#define YY_SKIP_YYWRAP
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 16
#define YY_END_OF_BUFFER 17
static yyconst short int yy_accept[262] =
    {   0,
        0,    0,   17,   15,   14,   14,   10,   15,   15,   10,
       15,   11,   10,   10,   15,   10,    3,    2,   10,   15,
       10,   12,   12,   12,   12,   12,   12,   12,   12,   12,
       12,   12,   12,   12,   12,   12,   12,   14,   10,    0,
       13,    0,    0,    0,    0,    5,    0,    8,    5,    3,
        0,    0,    0,    2,   12,   12,   12,   12,   12,   12,
       12,   12,    9,   12,   12,   12,   12,   12,   12,    9,
       12,   12,   12,   12,   12,   12,   12,   12,   12,   12,
       12,    0,    0,    6,    0,    5,    0,    0,    8,    0,
        5,    0,    5,    4,   12,   12,   12,   12,   12,   12,

       12,   12,   12,   12,   12,   12,    9,   12,    9,   12,
       12,   12,   12,   12,   12,   12,   12,   12,   12,   12,
       12,   12,   12,   12,    0,    0,    0,    5,    7,    0,
        5,    5,    9,   12,   12,   12,   12,   12,   12,   12,
       12,   12,   12,   12,   12,   12,   12,   12,   12,   12,
       12,   12,   12,    0,    0,   12,   12,   12,   12,   12,
       12,   12,   12,   12,   12,   12,   12,   12,   12,    0,
        0,   12,   12,   12,   10,   12,   12,   12,    0,    0,
       12,   12,   12,   12,    0,    0,    1,    1,    0,    0,
        1,    1,    1,    0,    0,    0,    1,    0,    1,    1,

        0,    0,    0,    0,    0,    1,    0,    1,    0,    1,
        1,    1,    1,    0,    0,    1,    1,    0,    0,    0,
        0,    0,    1,    0,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    0,    0,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    7,    1,    1,    8,    9,   10,
       11,   12,   13,   14,   15,   16,   17,   18,   19,   19,
       19,   19,   19,   19,   19,   20,   20,   21,   22,   23,
       24,   25,    1,    1,   26,   26,   26,   26,   27,   28,
       29,   29,   29,   29,   29,   30,   29,   29,   29,   29,
       29,   29,   29,   29,   29,   29,   29,   31,   29,   29,
        1,   32,    1,    1,   29,    1,   33,   34,   35,   36,

       37,   38,   39,   40,   41,   29,   42,   43,   44,   45,
       46,   47,   29,   48,   49,   50,   51,   52,   53,   54,
       55,   56,   57,    1,   58,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[59] =
    {   0,
        1,    1,    2,    3,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    3,    1,    4,    4,    4,
        1,    1,    1,    1,    1,    4,    4,    4,    5,    5,
        5,    1,    4,    4,    4,    4,    4,    4,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    1,    1
    } ;

static yyconst short int yy_base[273] =
    {   0,
        0,    0,  664,  665,   57,   60,  639,   59,   30,  665,
        0,  665,  649,  646,   49,   58,   58,   63,  636,  635,
      634,    0,  606,   38,   47,   51,   49,   53,  610,   60,
      609,  617,   61,  595,  600,  588,  582,  104,  665,   98,
      665,  611,  576,  567,  602,  113,  598,    0,  139,   97,
      102,  129,    0,  144,    0,  559,  562,  570,  557,  572,
      558,  564,  550,  551,  547,  547,  550,  547,  544,    0,
      543,  545,   86,  542,   70,   90,  546,  539,   78,   94,
      544,  546,  548,  665,  155,  665,  570,  166,    0,  171,
      665,  134,  174,    0,  531,  533,  542,  537,  525,   23,

      539,  537,  533,  525,  530,  533,    0,  519,    0,  525,
      522,  509,  511,  513,  520,  503,  501,  501,  513,  503,
      506,  505,  497,  486,  475,  466,  177,  180,  665,  187,
      196,  665,    0,  465,  442,  442,  431,  436,  430,  424,
      421,  417,  413,  420,  409,  409,  414,  404,  402,  391,
      368,  352,  363,  348,  341,  345,  345,  346,  337,  323,
      326,  333,  330,  329,  312,  321,  322,  313,  313,  302,
      302,  256,  251,  256,    0,  253,  251,  242,  209,  238,
      237,  222,  232,  211,  217,  212,  222,  227,  247,  197,
      259,  285,  253,  290,  237,    0,  313,  326,  347,  264,

      337,  288,  228,  206,  301,  665,  357,  665,  242,  361,
        0,    0,  306,  390,  407,  280,  367,  195,  139,  171,
      145,  316,  394,  329,  428,  665,  377,  397,  434,  449,
      457,  467,    0,  203,  327,    0,  471,  477,  400,  481,
        0,  486,  495,  411,  500,  164,  156,  441,  508,  504,
      514,  518,  524,    0,  561,    0,  134,  127,  227,    0,
      665,  615,  620,  622,  627,  632,  124,  635,  638,  106,
      643,  648
    } ;

static yyconst short int yy_def[273] =
    {   0,
      261,    1,  261,  261,  261,  261,  261,  262,  261,  261,
      263,  261,  261,  261,  261,  261,  261,  261,  261,  261,
      261,  264,  264,  264,  264,  264,  264,  264,  264,  264,
      264,  264,  264,  264,  264,  264,  264,  261,  261,  262,
      261,  262,  261,  261,  261,  261,  265,  266,  261,  261,
      261,  261,  267,  261,  264,  264,  264,  264,  264,  264,
      264,  264,  264,  264,  264,  264,  264,  264,  264,  264,
      264,  264,  264,  264,  264,  264,  264,  264,  264,  264,
      264,  261,  261,  261,  261,  261,  265,  265,  266,  261,
      261,  261,  261,  267,  264,  264,  264,  264,  264,  264,

      264,  264,  264,  264,  264,  264,  264,  264,  264,  264,
      264,  264,  264,  264,  264,  264,  264,  264,  264,  264,
      264,  264,  264,  264,  261,  261,  261,  261,  261,  261,
      261,  261,  264,  264,  264,  264,  264,  264,  264,  264,
      264,  264,  264,  264,  264,  264,  264,  264,  264,  264,
      264,  264,  264,  261,  261,  264,  264,  264,  264,  264,
      264,  264,  264,  264,  264,  264,  264,  264,  264,  261,
      261,  264,  264,  264,  264,  264,  264,  264,  268,  261,
      264,  264,  264,  264,  268,  261,  261,  261,  269,  261,
      261,  261,  261,  261,  261,  270,  261,  261,  269,  199,

      269,  261,  271,  272,  261,  261,  261,  261,  261,  261,
      270,  199,  199,  269,  269,  199,  199,  271,  271,  272,
      272,  261,  261,  261,  261,  261,  199,  199,  199,  229,
      215,  231,  215,  271,  272,  229,  229,  269,  229,  229,
      231,  231,  215,  231,  231,  271,  272,  229,  229,  231,
      231,  231,  252,  252,  231,  215,  255,  255,  255,  255,
        0,  261,  261,  261,  261,  261,  261,  261,  261,  261,
      261,  261
    } ;

static yyconst short int yy_nxt[724] =
    {   0,
        4,    5,    6,    5,    7,    8,    9,   10,   11,   12,
       12,   10,   13,   12,   14,   15,   16,   17,   18,   18,
       12,   12,   19,   20,   21,   22,   22,   22,   22,   22,
       22,    4,   23,   24,   25,   26,   27,   28,   29,   22,
       30,   22,   31,   22,   22,   22,   22,   32,   33,   34,
       35,   36,   37,   22,   22,   22,   12,   12,   38,   38,
       38,   38,   38,   38,   41,   43,   46,   46,   46,   47,
       44,  135,  136,   49,   48,   50,   50,   51,   49,   59,
       54,   54,   54,   57,   52,   58,   60,   62,   53,   52,
       42,   64,   61,   65,   52,   67,   63,   70,   68,   52,

       74,   75,   66,   41,   71,   38,   38,   38,  114,  211,
       76,   53,   49,   77,   50,   50,   51,   49,  120,   51,
       51,   51,  116,   52,  111,  115,  121,   94,   52,   42,
       46,   46,   46,   52,  122,  112,  123,  117,   52,   85,
       86,   92,   86,   92,  257,  258,   93,   93,   93,   85,
       86,   93,   93,   93,  219,   86,   46,   46,   46,   49,
      221,   54,   54,   54,  215,   90,   91,  127,   91,  127,
       52,  221,  128,  128,  128,   90,   91,   88,  234,  219,
       52,   91,  129,  130,  235,  130,  221,  215,  131,  131,
      131,   93,   93,   93,  128,  128,  128,  128,  128,  128,

      202,  132,  203,  132,  131,  131,  131,   86,  246,   86,
      219,  132,  185,  131,  131,  131,  132,   86,  219,  204,
      185,  221,   86,   91,  186,   91,  187,  188,  188,  191,
      191,  191,  186,   91,  187,  188,  188,  192,   91,  193,
      193,  194,  192,  219,  197,  197,  197,  133,  195,  209,
      198,  209,  196,  195,  210,  210,  210,  215,  195,  210,
      210,  210,  186,  195,  199,  200,  200,  109,  192,  133,
      193,  193,  194,  133,  190,  196,  191,  191,  191,  195,
      215,  216,  217,  217,  184,  205,  206,  183,  206,  195,
      109,  202,  182,  203,  201,  205,  206,  227,  228,  217,

       70,  206,  191,  191,  191,  192,  181,  194,  194,  194,
      204,  207,  208,  222,  208,  222,  195,  201,  223,  223,
      223,  207,  208,  227,  228,  217,  195,  208,  192,  198,
      197,  197,  197,  223,  223,  223,  201,  180,  179,  195,
      198,  186,  221,  187,  188,  188,  225,  225,  225,  195,
      198,  247,  186,  178,  199,  200,  200,  177,  176,  201,
       70,  109,  192,  133,  212,  213,  200,  175,  109,  224,
       70,  224,  174,  214,  225,  225,  225,  215,  210,  210,
      210,  133,  109,  214,  216,  217,  217,  173,  226,  172,
      226,  171,  170,  198,  227,  228,  217,  201,  226,  107,

      215,  169,  209,  226,  209,  186,  168,  229,  230,  230,
      198,  223,  223,  223,  227,  228,  217,  248,  249,  240,
      201,  206,  186,  206,  231,  232,  232,  201,  250,  251,
      245,  206,  233,  233,  233,  133,  206,  167,  166,  233,
      233,  233,  233,  233,  233,  225,  225,  225,  165,  164,
      201,  236,  237,  230,  163,  208,  162,  208,  248,  249,
      240,  238,  109,  238,  161,  208,  239,  240,  240,  160,
      208,  238,  192,  109,  241,  242,  238,  159,  158,  201,
      198,  157,  156,  243,  244,  245,  245,  215,  248,  249,
      240,  109,  186,  243,  199,  200,  200,  201,  239,  240,

      240,  201,  201,  250,  251,  245,   70,  209,  155,  209,
      215,  201,  252,  253,  253,  154,  201,  244,  245,  245,
      201,  250,  251,  245,  201,  248,  249,  240,  153,  152,
      201,  250,  251,  245,  201,  254,  255,  253,  201,  201,
      133,  257,  258,  258,  201,  256,  151,  238,  150,  149,
      148,  147,  146,  201,  201,  256,  145,  144,  143,  142,
      238,  201,  141,  109,  133,  140,  139,  201,  109,   70,
      138,  137,  109,   70,  134,  109,  133,  201,  259,  260,
      258,   88,  126,  125,  124,  119,  118,  113,  256,  110,
      238,  201,  109,  108,  107,  106,  105,  104,  256,  103,

      102,  101,  100,  238,   99,   98,   97,   96,   95,   88,
       84,   83,   82,  261,  201,   40,   40,   40,   40,   40,
       45,   81,   45,   45,   45,   55,   55,   87,   87,   87,
       87,   87,   89,   80,   89,   89,   89,  189,  189,  189,
      201,  201,  201,  218,   79,  218,  218,  218,  220,   78,
      220,  220,  220,   73,   72,   69,   56,   39,   39,   39,
       39,   39,   39,  261,    3,  261,  261,  261,  261,  261,
      261,  261,  261,  261,  261,  261,  261,  261,  261,  261,
      261,  261,  261,  261,  261,  261,  261,  261,  261,  261,
      261,  261,  261,  261,  261,  261,  261,  261,  261,  261,

      261,  261,  261,  261,  261,  261,  261,  261,  261,  261,
      261,  261,  261,  261,  261,  261,  261,  261,  261,  261,
      261,  261,  261
    } ;

static yyconst short int yy_chk[724] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    5,    5,
        5,    6,    6,    6,    8,    9,   15,   15,   15,   16,
        9,  100,  100,   17,   16,   17,   17,   17,   18,   25,
       18,   18,   18,   24,   17,   24,   25,   26,   17,   18,
        8,   27,   25,   27,   17,   28,   26,   30,   28,   18,

       33,   33,   27,   40,   30,   38,   38,   38,   75,  270,
       33,   17,   50,   33,   50,   50,   50,   51,   79,   51,
       51,   51,   76,   50,   73,   75,   79,  267,   51,   40,
       46,   46,   46,   50,   80,   73,   80,   76,   51,   46,
       46,   52,   46,   52,  258,  258,   52,   52,   52,   46,
       46,   92,   92,   92,  219,   46,   49,   49,   49,   54,
      221,   54,   54,   54,  257,   49,   49,   85,   49,   85,
       54,  247,   85,   85,   85,   49,   49,   88,  219,  246,
       54,   49,   88,   90,  221,   90,  220,  257,   90,   90,
       90,   93,   93,   93,  127,  127,  127,  128,  128,  128,

      190,   93,  190,   93,  130,  130,  130,  128,  234,  128,
      218,   93,  179,  131,  131,  131,   93,  128,  234,  190,
      185,  204,  128,  131,  179,  131,  179,  179,  179,  186,
      186,  186,  185,  131,  185,  185,  185,  187,  131,  187,
      187,  187,  188,  203,  188,  188,  188,  184,  187,  195,
      189,  195,  187,  188,  195,  195,  195,  259,  187,  209,
      209,  209,  189,  188,  189,  189,  189,  183,  193,  182,
      193,  193,  193,  181,  180,  187,  191,  191,  191,  193,
      259,  200,  200,  200,  178,  191,  191,  177,  191,  193,
      176,  202,  174,  202,  200,  191,  191,  216,  216,  216,

      173,  191,  192,  192,  192,  194,  172,  194,  194,  194,
      202,  192,  192,  205,  192,  205,  194,  200,  205,  205,
      205,  192,  192,  213,  213,  213,  194,  192,  197,  198,
      197,  197,  197,  222,  222,  222,  213,  171,  170,  197,
      201,  198,  235,  198,  198,  198,  224,  224,  224,  197,
      199,  235,  201,  169,  201,  201,  201,  168,  167,  213,
      166,  165,  199,  164,  199,  199,  199,  163,  162,  207,
      161,  207,  160,  199,  207,  207,  207,  199,  210,  210,
      210,  159,  158,  199,  217,  217,  217,  157,  210,  156,
      210,  155,  154,  214,  227,  227,  227,  217,  210,  153,

      199,  152,  214,  210,  214,  214,  151,  214,  214,  214,
      215,  223,  223,  223,  228,  228,  228,  239,  239,  239,
      217,  223,  215,  223,  215,  215,  215,  228,  244,  244,
      244,  223,  215,  215,  215,  150,  223,  149,  148,  215,
      215,  215,  215,  215,  215,  225,  225,  225,  147,  146,
      228,  229,  229,  229,  145,  225,  144,  225,  248,  248,
      248,  229,  143,  229,  142,  225,  230,  230,  230,  141,
      225,  229,  231,  140,  231,  231,  229,  139,  138,  230,
      238,  137,  136,  231,  232,  232,  232,  231,  237,  237,
      237,  135,  238,  231,  238,  238,  238,  232,  240,  240,

      240,  237,  230,  242,  242,  242,  134,  243,  126,  243,
      231,  240,  243,  243,  243,  125,  242,  245,  245,  245,
      232,  250,  250,  250,  237,  249,  249,  249,  124,  123,
      245,  251,  251,  251,  240,  252,  252,  252,  249,  242,
      122,  253,  253,  253,  251,  252,  121,  252,  120,  119,
      118,  117,  116,  245,  253,  252,  115,  114,  113,  112,
      252,  249,  111,  110,  108,  106,  105,  251,  104,  103,
      102,  101,   99,   98,   97,   96,   95,  253,  255,  255,
      255,   87,   83,   82,   81,   78,   77,   74,  255,   72,
      255,  255,   71,   69,   68,   67,   66,   65,  255,   64,

       63,   62,   61,  255,   60,   59,   58,   57,   56,   47,
       45,   44,   43,   42,  255,  262,  262,  262,  262,  262,
      263,   37,  263,  263,  263,  264,  264,  265,  265,  265,
      265,  265,  266,   36,  266,  266,  266,  268,  268,  268,
      269,  269,  269,  271,   35,  271,  271,  271,  272,   34,
      272,  272,  272,   32,   31,   29,   23,   21,   20,   19,
       14,   13,    7,    3,  261,  261,  261,  261,  261,  261,
      261,  261,  261,  261,  261,  261,  261,  261,  261,  261,
      261,  261,  261,  261,  261,  261,  261,  261,  261,  261,
      261,  261,  261,  261,  261,  261,  261,  261,  261,  261,

      261,  261,  261,  261,  261,  261,  261,  261,  261,  261,
      261,  261,  261,  261,  261,  261,  261,  261,  261,  261,
      261,  261,  261
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "TP3.l"
#define INITIAL 0
#line 3 "TP3.l"

#include<stdio.h>
#include<math.h> 
#include<stdlib.h>
#include<string.h>
#include "funcionesTP3.h"
int acum = 0;
int valor= 0;


//Implementar en C un programa que permita reconocer en un archivo.c de entrada todas las 
//categorías léxicas de C y comentarios. El mismo deberá  dar como salida en pantalla un 
//reporte. Para desarrollar dicho programa deberá utilizar LEX/FLEX para la generación del 
//código C que implemente el analizador léxico.



//Categorías léxicas de C a reconocer:
//      Constantes (Entera decimal, entera octal, entera hexadecimal, real, caracter) x
//      Literal cadena x
//      Palabras reservadas (distinguir entre tipo de dato, estructuras de control y otros) 
//      Identificadores x
//      Caracteres de puntuación y operadores de C.

//Comentarios (es realidad son reconocidos por el PRECOMPILADOR)
//      Comentarios de una línea x
//      Comentarios de múltiples líneas x

//Reporte
//  Listado de identificadores encontrados indicando la cantidad de veces que aparece cada uno de ellos. 
//  El listado debe estar ordenado alfabéticamente.
//  Listado de literales cadena encontrados indicando la longitud de los mismos.
//  Listado de palabras reservadas en el orden en el que han aparecido.
//  Listado de constantes indicando según su tipo:
//          Para las constantes octales indicar su valor entero decimal.
//          Para las constante hexadecimales indicar su valor entero decimal.
//          Para las constantes decimales indicar el valor de cada una y el total acumulado de sumar todas ellas.
//          Para las constantes reales indicar el valor de su mantisa y parte entera.
//          Para las constantes caracter, enumerarlas según orden de aparición. 
//  Listado de operadores/caracteres de puntuación indicando cantidad de veces que aparecen.
//  Listado de comentarios encontrados distinguiendo si se trata de comentarios de una línea o múltiples líneas.
//  Listado de cadenas y/o caracteres no reconocidos indicando el número de línea.

//Desafío opcional
//  Adicionar al analizador léxico el reconocimiento de las directivas del precompilador #Include #Define.

//-----------------------------------------------------------------------------------------------------------------
//------------------------------------------------------------------------------------------------------------------

//   COSAS PARA ARREGLAR - AGREGAR

//Faltan algunos COP y CPU
//Luego ordenar la prioridad de reglas
//Probar reglas una vez completadas y armar palabras para reconocer en el txt y luego en el .c
//crear listas para recorrer y cumplir lo pedido:
/*  Listado de id falta ordenar alfabeticamente
    Listado de lt falta obviar las comillas dado que las comillas las toma como caracteres, por ejemplo,
      "hola" yyleng retorna 6, en realidad tendria que devolver 4-> hacer una funcion que obvie las comillas
    Listado de pr falta decidir cosas
    Listado de constantes:
                     dec falta una funcion que sume todos los valores de la lista (REVISAR)
                     real faltaria una funcion o dos que devuelvan la parte mantisa y entera de un creal
    Listado de car no reconocidos falta lo de ver en que linea fueron encontrados, que alguien vea los videos
      habia hecho algo el profe
*/
//Revisar el #define

//-------------------------------------------------------------------------------------------------------------------
//-------------------------------------------------------------------------------------------------------------------


#line 687 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 101 "TP3.l"


#line 841 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 262 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 665 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 103 "TP3.l"
{printf("La cadena %s representa una directiva al compilador\n", yytext);}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 105 "TP3.l"
{acum = acum + atoi(yytext); printf("El valor acumulado es %d\n", acum);
                        cdec = verificarCadena(cdec,yytext);}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 108 "TP3.l"
{printf("La cadena %s representa una constante entera octal\n", yytext);
                        int oct=(int)strtol(yytext, NULL, 0);
                        //int oct =OctalADecimal(atoi(yytext));
                        coct = verificarCadena2(coct,yytext,oct);
                        }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 114 "TP3.l"
{printf("La cadena %s representa una constante entera hexadecimal\n", yytext);
                        int hex=(int)strtol(yytext, NULL, 0);
                        chex = verificarCadena2(chex,yytext,hex);
} 
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 119 "TP3.l"
{printf("La cadena %s representa una constante real\n", yytext);
                        }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 122 "TP3.l"
{acum= acum+1; printf("La cadena %s representa un caracter\n", yytext);
                        ccar = verificarCadena3(ccar,yytext);}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 125 "TP3.l"
{printf("La cadena %s representa un comentario de multiples lineas\n", yytext);} 
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 127 "TP3.l"
{printf("La cadena %s representa un comentario simple\n", yytext);} 
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 129 "TP3.l"
{printf("La cadena %s representa una palabra reservada para representar un tipo de dato\n", yytext);
                        pr = verificarCadena3(pr,yytext);}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 132 "TP3.l"
{printf("La cadena %s representa un caracter de operacion\n", yytext);
                          cop = verificarCadena(cop,yytext);}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 135 "TP3.l"
{printf("La cadena %s representa un caracter de puntuacion\n", yytext);
                          cpu = verificarCadena(cpu,yytext);}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 138 "TP3.l"
{printf("La cadena %s representa un identificador\n", yytext);
                          id =verificarCadena(id,yytext);}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 141 "TP3.l"
{printf("La cadena %s representa un literal cadena de %d caracteres\n", yytext,yyleng);
                          lt =verificarCadena2(lt,yytext,yyleng);}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 144 "TP3.l"

	YY_BREAK
case 15:
YY_RULE_SETUP
#line 145 "TP3.l"
{printf("La cadena %s representa un caracter no reconocido\n", yytext);}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 147 "TP3.l"
ECHO;
	YY_BREAK
#line 1019 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 262 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 262 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 261);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 147 "TP3.l"



int main(){
    
    yyin = fopen("entrada.txt","r");
    yylex();
    //int x = 0xf;
    //printf("%d",x);
    imprimirOpciones();
    return 0;
}












    //COMENTARIOS, DUDAS Y CAMBIOS

    //Cambie la regla de comentarios: "//"(.)*\n|"/*"(.|\n)*"*/" por dos distintas para identificar entre comentarios simples y multiples
    //agrego funcion para pasar de hexa a decimal 
    //agrego funcion para pasar de octal a decimal 
    //agrego funcion para sumar los elementos de la lista (esta está polemica ajajs revisenla y fijense)
    //Agregue todas las palabras reservadas que faltaban, y las reagrupe en una sola regla para que quede un poco mas simple
    //Agregue una definicion para #define, pero me parece que queda otra mas, la de los ejemplos que estan en el archivo de entrada funcionan bien
    //Agregue un par de caracteres de puntuacion y operacion que faltaban (Puede que falte alguno todavia, revisar lo del sizeof)
    //Modifique un poco el menu para que no parezca que te esta gritando con las mayusculas jajaj
    /*Pense en modificar la defincion de constantes reales, pero tendria que hacer como definciones que "abarquen" pocos caracteres y no se que tan expresivo queda
    pero en si la definicion esta bien asi */
    //Acomode un poco los archivos para que no quede todo tan mezclado
    //No se que tanto mas se pueden "delegar" las definiciones usando reglas que ya estan, habria que cambiar casi TODAS y no se si queda tan expresivo en definitiva


    

    //ESTRUCTURA DEL ARCHIVO.L:

    //%{
    // DEFINICIONES Y DECLARACIONES DE C
    // }%

    // DEFINICIONES (NOMBRE EXR) -> Se definen nombres para las ERX

    // %%

    // REGLAS (ERX - CÓDIGO C) -> Conocido como PATRÓN/ACCIÓN

    // %%

    // CÓDIGO C DE USUARIO -> Código C que ejecuta el analizador léxico
 






 // COSAS CORREGIDAS Y LISTAS (Borrar despues)

//No deberia ser un archivo .c como entrada? 
//Si solo use el txt para ir probando antes de mandarlo al .c ya que no me andara hinchando con los errores
//lo vuelvo a poner para hacer una pre prueba en el txt y luego el mismo en .c

//ademas tengo duda con el archivo de salida, no es innecesario? 
//Es como decis no es necesario, pensaba en usarlo como un reporte final para que quede mas
//presentable con todos los reportes en la salida.txt si llegamos seria bueno ponerlo a demas de por consola
// que lo pensaba como un menu de opciones 

//(Hice una clasificacion pero tal vez puede simplifacarse o reordenarse) sobre palabras reservadas
//bien, alguien que la revise y vea si puede agregar mas dado que por internet rondaban entre 32 y 40
//como dije en las cosas por hacer que las revisen si no pueden usarse como identificador entonces esas van

//Agregue un menu de opciones con la funcion de mostrar todos los casos para probarlo
//Esta genial el menu :O, le modifique un par de cosas, obvio funciona ahora pero da siempre la lista de id
// mas adelante hay que modificarlo cuando tengamos las listas, ponele algo de minuscula hay mucha mayuscula jaja
/* Algo asi solo a los que tienen nro
1)Listado de identificadores encontrados y su cantidad de veces
*/

// si hay que comentarlas usemos  /* */ porque sino linea por linea es un bardo  
// si lo tendre en cuanta para el prox commit es que usaba teclas de acceso rapido por eso y me comenta
// todo asi cuando selecciono y le doy con "crtl }" 

//funcion que "propias de c" que podramos usar expliquen para que sirve

//Encontre una funcion: strtol(const char *str, char **endptr, int base) , que lo que hace es convertir el valor hexa a decimal
//aunque no entiendo por que no me covierte la cadena hexa que encontro a decimal ¿??
// En si en la funcion "str" es la cadena principal
// "endptr" seria la parte de caracteres luego del ultimo caracter numerico
//lo que hace la funcion es retornar un long int que es la parte numerica de la cadena principal "str"
// EJEMPLO  hexaEnDec= (int)strtol("0X2 asdk", luegoDePrtNum, 16);
//Creas una variable hexaEnDec por asi decir y lo que retorna la funcion lo convertis en int con casteo (int)
//,y una variable luegoDePrtNum que no te sirve para nada pero no podes dejarlo vacio y base 16
// tambien podes buscar una funcion hecha en c que quizas haya en internet sino funciona con strtol


//Agregue las directivas que faltan. Son muchisimas, y creo que el tp pide solo #define y #include
    //Entonces solo esas, faltaria la de define nada mas 


/* En la lista de pr se puede simplificar porque las acciones en las reglas de pr son iguales
Opciones
1) quiza lo ponemos todo en una definicion de pr y luego en la lista o acciones lo clasificamos
2) ya que esta clasificado en definiciones quizas lo unificamos en una regla con un "|" 
no recuerdo si se puede, y como queda una sola regla no repetimos acciones */

//Lo de hex a dec da mal hay que verlo 





